---
name: cobench
on:
  schedule:
    - cron: "23 23 * * *"
  push:
    branches:
      - master
jobs:
  cobench:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: gem install cobench
      - run: cobench --verbose --token ${{ secrets.TOKEN }} --to gh-pages --days 21
      - uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: gh-pages
          clean: false
